2022-02-28 13:17:09,179 INFO    MainThread:621286 [wandb_setup.py:_flush():71] setting env: {}
2022-02-28 13:17:09,179 INFO    MainThread:621286 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-28 13:17:09,179 INFO    MainThread:621286 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-28 13:17:09,180 INFO    MainThread:621286 [wandb_init.py:_log_setup():371] Logging user logs to /home/junshick/Workspace/pose_estimation/custom_pose/wandb/run-20220228_131709-1tch985c/logs/debug.log
2022-02-28 13:17:09,180 INFO    MainThread:621286 [wandb_init.py:_log_setup():372] Logging internal logs to /home/junshick/Workspace/pose_estimation/custom_pose/wandb/run-20220228_131709-1tch985c/logs/debug-internal.log
2022-02-28 13:17:09,180 INFO    MainThread:621286 [wandb_init.py:init():404] calling init triggers
2022-02-28 13:17:09,180 INFO    MainThread:621286 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2022-02-28 13:17:09,180 INFO    MainThread:621286 [wandb_init.py:init():460] starting backend
2022-02-28 13:17:09,180 INFO    MainThread:621286 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-28 13:17:09,188 INFO    MainThread:621286 [backend.py:ensure_launched():216] starting backend process...
2022-02-28 13:17:09,191 INFO    MainThread:621286 [backend.py:ensure_launched():222] started backend process with pid: 621295
2022-02-28 13:17:09,192 INFO    MainThread:621286 [wandb_init.py:init():469] backend started and connected
2022-02-28 13:17:09,194 INFO    MainThread:621286 [wandb_init.py:init():533] updated telemetry
2022-02-28 13:17:09,195 INFO    MainThread:621286 [wandb_init.py:init():563] communicating current version
2022-02-28 13:17:09,644 INFO    MainThread:621286 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.10 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-02-28 13:17:09,644 INFO    MainThread:621286 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-02-28 13:17:09,953 INFO    MainThread:621286 [wandb_init.py:init():606] starting run threads in backend
2022-02-28 13:17:12,495 INFO    MainThread:621286 [wandb_run.py:_console_start():1810] atexit reg
2022-02-28 13:17:12,496 INFO    MainThread:621286 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2022-02-28 13:17:12,496 INFO    MainThread:621286 [wandb_run.py:_redirect():1689] Redirecting console.
2022-02-28 13:17:12,497 INFO    MainThread:621286 [wandb_run.py:_redirect():1745] Redirects installed.
2022-02-28 13:17:12,497 INFO    MainThread:621286 [wandb_init.py:init():633] run started, returning control to user process
2022-02-28 13:17:28,167 INFO    MainThread:621286 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 1
2022-02-28 13:17:28,168 INFO    MainThread:621286 [wandb_run.py:_restore():1752] restore
2022-02-28 13:17:31,024 INFO    MainThread:621286 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 681
  total_bytes: 681
}

2022-02-28 13:17:31,398 INFO    MainThread:621286 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 681
  total_bytes: 681
}

2022-02-28 13:17:31,964 INFO    MainThread:621286 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 681
  total_bytes: 681
}

2022-02-28 13:17:32,065 INFO    MainThread:621286 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 681
  total_bytes: 15910
}

2022-02-28 13:17:32,168 INFO    MainThread:621286 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 681
  total_bytes: 15910
}

2022-02-28 13:17:32,270 INFO    MainThread:621286 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 681
  total_bytes: 15910
}

2022-02-28 13:17:32,372 INFO    MainThread:621286 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15910
  total_bytes: 15910
}

2022-02-28 13:17:32,474 INFO    MainThread:621286 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15910
  total_bytes: 15910
}

2022-02-28 13:17:32,577 INFO    MainThread:621286 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15910
  total_bytes: 15910
}

2022-02-28 13:17:32,679 INFO    MainThread:621286 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15910
  total_bytes: 15910
}

2022-02-28 13:17:32,782 INFO    MainThread:621286 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15910
  total_bytes: 15910
}

2022-02-28 13:17:33,176 INFO    MainThread:621286 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15910
  total_bytes: 15910
}

2022-02-28 13:17:33,728 INFO    MainThread:621286 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15910
  total_bytes: 15910
}
local_info {
}

2022-02-28 13:17:34,794 INFO    MainThread:621286 [wandb_run.py:_append_history():2130] rendering history
2022-02-28 13:17:34,794 INFO    MainThread:621286 [wandb_run.py:_append_summary():2085] rendering summary
2022-02-28 13:17:34,794 INFO    MainThread:621286 [wandb_run.py:_append_files():2180] logging synced files
