2022-03-04 10:33:28,541 INFO    MainThread:669312 [wandb_setup.py:_flush():71] setting env: {}
2022-03-04 10:33:28,542 INFO    MainThread:669312 [wandb_setup.py:_flush():71] setting login settings: {}
2022-03-04 10:33:28,542 INFO    MainThread:669312 [wandb_setup.py:_flush():71] setting login settings: {}
2022-03-04 10:33:28,542 INFO    MainThread:669312 [wandb_init.py:_log_setup():371] Logging user logs to /home/junshick/Workspace/pose_estimation/custom_pose/wandb/run-20220304_103328-3m5w4qus/logs/debug.log
2022-03-04 10:33:28,542 INFO    MainThread:669312 [wandb_init.py:_log_setup():372] Logging internal logs to /home/junshick/Workspace/pose_estimation/custom_pose/wandb/run-20220304_103328-3m5w4qus/logs/debug-internal.log
2022-03-04 10:33:28,542 INFO    MainThread:669312 [wandb_init.py:init():404] calling init triggers
2022-03-04 10:33:28,542 INFO    MainThread:669312 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2022-03-04 10:33:28,542 INFO    MainThread:669312 [wandb_init.py:init():460] starting backend
2022-03-04 10:33:28,542 INFO    MainThread:669312 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-04 10:33:28,550 INFO    MainThread:669312 [backend.py:ensure_launched():216] starting backend process...
2022-03-04 10:33:28,553 INFO    MainThread:669312 [backend.py:ensure_launched():222] started backend process with pid: 669321
2022-03-04 10:33:28,554 INFO    MainThread:669312 [wandb_init.py:init():469] backend started and connected
2022-03-04 10:33:28,556 INFO    MainThread:669312 [wandb_init.py:init():533] updated telemetry
2022-03-04 10:33:28,568 INFO    MainThread:669312 [wandb_init.py:init():563] communicating current version
2022-03-04 10:33:29,017 INFO    MainThread:669312 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-03-04 10:33:29,017 INFO    MainThread:669312 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-03-04 10:33:29,346 INFO    MainThread:669312 [wandb_init.py:init():606] starting run threads in backend
2022-03-04 10:33:31,956 INFO    MainThread:669312 [wandb_run.py:_console_start():1810] atexit reg
2022-03-04 10:33:31,956 INFO    MainThread:669312 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2022-03-04 10:33:31,956 INFO    MainThread:669312 [wandb_run.py:_redirect():1689] Redirecting console.
2022-03-04 10:33:31,957 INFO    MainThread:669312 [wandb_run.py:_redirect():1745] Redirects installed.
2022-03-04 10:33:31,958 INFO    MainThread:669312 [wandb_init.py:init():633] run started, returning control to user process
2022-03-04 10:33:34,169 INFO    MainThread:669312 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 1
2022-03-04 10:33:34,171 INFO    MainThread:669312 [wandb_run.py:_restore():1752] restore
2022-03-04 10:33:36,969 INFO    MainThread:669312 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 766
}

2022-03-04 10:33:37,369 INFO    MainThread:669312 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 766
}

2022-03-04 10:33:38,358 INFO    MainThread:669312 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 15569
}

2022-03-04 10:33:38,461 INFO    MainThread:669312 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 15569
}

2022-03-04 10:33:38,562 INFO    MainThread:669312 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 15569
}

2022-03-04 10:33:38,665 INFO    MainThread:669312 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5257
  total_bytes: 15569
}

2022-03-04 10:33:38,766 INFO    MainThread:669312 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5257
  total_bytes: 15569
}

2022-03-04 10:33:38,869 INFO    MainThread:669312 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15569
  total_bytes: 15569
}

2022-03-04 10:33:38,971 INFO    MainThread:669312 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15569
  total_bytes: 15569
}

2022-03-04 10:33:39,073 INFO    MainThread:669312 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15569
  total_bytes: 15569
}

2022-03-04 10:33:39,176 INFO    MainThread:669312 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15569
  total_bytes: 15569
}

2022-03-04 10:33:39,278 INFO    MainThread:669312 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15569
  total_bytes: 15569
}

2022-03-04 10:33:39,380 INFO    MainThread:669312 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15569
  total_bytes: 15569
}

2022-03-04 10:33:39,655 INFO    MainThread:669312 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15569
  total_bytes: 15569
}

2022-03-04 10:33:40,216 INFO    MainThread:669312 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15569
  total_bytes: 15569
}
local_info {
}

2022-03-04 10:33:41,281 INFO    MainThread:669312 [wandb_run.py:_append_files():2180] logging synced files
