2022-03-04 11:09:34,943 INFO    MainThread:669714 [wandb_setup.py:_flush():71] setting env: {}
2022-03-04 11:09:34,943 INFO    MainThread:669714 [wandb_setup.py:_flush():71] setting login settings: {}
2022-03-04 11:09:34,943 INFO    MainThread:669714 [wandb_setup.py:_flush():71] setting login settings: {}
2022-03-04 11:09:34,943 INFO    MainThread:669714 [wandb_init.py:_log_setup():371] Logging user logs to /home/junshick/Workspace/pose_estimation/custom_pose/wandb/run-20220304_110934-2bfvbftk/logs/debug.log
2022-03-04 11:09:34,943 INFO    MainThread:669714 [wandb_init.py:_log_setup():372] Logging internal logs to /home/junshick/Workspace/pose_estimation/custom_pose/wandb/run-20220304_110934-2bfvbftk/logs/debug-internal.log
2022-03-04 11:09:34,943 INFO    MainThread:669714 [wandb_init.py:init():404] calling init triggers
2022-03-04 11:09:34,943 INFO    MainThread:669714 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2022-03-04 11:09:34,943 INFO    MainThread:669714 [wandb_init.py:init():460] starting backend
2022-03-04 11:09:34,943 INFO    MainThread:669714 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-04 11:09:34,949 INFO    MainThread:669714 [backend.py:ensure_launched():216] starting backend process...
2022-03-04 11:09:34,953 INFO    MainThread:669714 [backend.py:ensure_launched():222] started backend process with pid: 669723
2022-03-04 11:09:34,953 INFO    MainThread:669714 [wandb_init.py:init():469] backend started and connected
2022-03-04 11:09:34,955 INFO    MainThread:669714 [wandb_init.py:init():533] updated telemetry
2022-03-04 11:09:34,962 INFO    MainThread:669714 [wandb_init.py:init():563] communicating current version
2022-03-04 11:09:35,419 INFO    MainThread:669714 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-03-04 11:09:35,419 INFO    MainThread:669714 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-03-04 11:09:35,708 INFO    MainThread:669714 [wandb_init.py:init():606] starting run threads in backend
2022-03-04 11:09:38,268 INFO    MainThread:669714 [wandb_run.py:_console_start():1810] atexit reg
2022-03-04 11:09:38,269 INFO    MainThread:669714 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2022-03-04 11:09:38,269 INFO    MainThread:669714 [wandb_run.py:_redirect():1689] Redirecting console.
2022-03-04 11:09:38,270 INFO    MainThread:669714 [wandb_run.py:_redirect():1745] Redirects installed.
2022-03-04 11:09:38,270 INFO    MainThread:669714 [wandb_init.py:init():633] run started, returning control to user process
2022-03-04 11:09:40,493 INFO    MainThread:669714 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 1
2022-03-04 11:09:40,495 INFO    MainThread:669714 [wandb_run.py:_restore():1752] restore
2022-03-04 11:09:43,282 INFO    MainThread:669714 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 766
}

2022-03-04 11:09:43,636 INFO    MainThread:669714 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 766
}

2022-03-04 11:09:43,738 INFO    MainThread:669714 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 15569
}

2022-03-04 11:09:43,840 INFO    MainThread:669714 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 15569
}

2022-03-04 11:09:43,943 INFO    MainThread:669714 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 15569
}

2022-03-04 11:09:44,045 INFO    MainThread:669714 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 14856
  total_bytes: 15569
}

2022-03-04 11:09:44,147 INFO    MainThread:669714 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15569
  total_bytes: 15569
}

2022-03-04 11:09:44,250 INFO    MainThread:669714 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15569
  total_bytes: 15569
}

2022-03-04 11:09:44,352 INFO    MainThread:669714 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15569
  total_bytes: 15569
}

2022-03-04 11:09:44,455 INFO    MainThread:669714 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15569
  total_bytes: 15569
}

2022-03-04 11:09:44,557 INFO    MainThread:669714 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15569
  total_bytes: 15569
}

2022-03-04 11:09:44,660 INFO    MainThread:669714 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15569
  total_bytes: 15569
}

2022-03-04 11:09:44,960 INFO    MainThread:669714 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15569
  total_bytes: 15569
}

2022-03-04 11:09:45,588 INFO    MainThread:669714 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15569
  total_bytes: 15569
}
local_info {
}

2022-03-04 11:09:46,654 INFO    MainThread:669714 [wandb_run.py:_append_files():2180] logging synced files
