2022-03-07 07:53:01,169 INFO    MainThread:699817 [wandb_setup.py:_flush():71] setting env: {}
2022-03-07 07:53:01,170 INFO    MainThread:699817 [wandb_setup.py:_flush():71] setting login settings: {}
2022-03-07 07:53:01,170 INFO    MainThread:699817 [wandb_setup.py:_flush():71] setting login settings: {}
2022-03-07 07:53:01,170 INFO    MainThread:699817 [wandb_init.py:_log_setup():371] Logging user logs to /home/junshick/Workspace/pose_estimation/custom_pose/wandb/run-20220307_075301-1wu3hbm3/logs/debug.log
2022-03-07 07:53:01,170 INFO    MainThread:699817 [wandb_init.py:_log_setup():372] Logging internal logs to /home/junshick/Workspace/pose_estimation/custom_pose/wandb/run-20220307_075301-1wu3hbm3/logs/debug-internal.log
2022-03-07 07:53:01,170 INFO    MainThread:699817 [wandb_init.py:init():404] calling init triggers
2022-03-07 07:53:01,170 INFO    MainThread:699817 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2022-03-07 07:53:01,170 INFO    MainThread:699817 [wandb_init.py:init():460] starting backend
2022-03-07 07:53:01,170 INFO    MainThread:699817 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-07 07:53:01,176 INFO    MainThread:699817 [backend.py:ensure_launched():216] starting backend process...
2022-03-07 07:53:01,179 INFO    MainThread:699817 [backend.py:ensure_launched():222] started backend process with pid: 699826
2022-03-07 07:53:01,180 INFO    MainThread:699817 [wandb_init.py:init():469] backend started and connected
2022-03-07 07:53:01,181 INFO    MainThread:699817 [wandb_init.py:init():533] updated telemetry
2022-03-07 07:53:01,188 INFO    MainThread:699817 [wandb_init.py:init():563] communicating current version
2022-03-07 07:53:01,624 INFO    MainThread:699817 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-03-07 07:53:01,624 INFO    MainThread:699817 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-03-07 07:53:01,885 INFO    MainThread:699817 [wandb_init.py:init():606] starting run threads in backend
2022-03-07 07:53:04,527 INFO    MainThread:699817 [wandb_run.py:_console_start():1810] atexit reg
2022-03-07 07:53:04,527 INFO    MainThread:699817 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2022-03-07 07:53:04,527 INFO    MainThread:699817 [wandb_run.py:_redirect():1689] Redirecting console.
2022-03-07 07:53:04,529 INFO    MainThread:699817 [wandb_run.py:_redirect():1745] Redirects installed.
2022-03-07 07:53:04,529 INFO    MainThread:699817 [wandb_init.py:init():633] run started, returning control to user process
2022-03-07 07:53:06,744 INFO    MainThread:699817 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 1
2022-03-07 07:53:06,745 INFO    MainThread:699817 [wandb_run.py:_restore():1752] restore
2022-03-07 07:53:09,541 INFO    MainThread:699817 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 766
}

2022-03-07 07:53:09,937 INFO    MainThread:699817 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 766
}

2022-03-07 07:53:10,898 INFO    MainThread:699817 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 15674
}

2022-03-07 07:53:11,000 INFO    MainThread:699817 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 15674
}

2022-03-07 07:53:11,102 INFO    MainThread:699817 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 15674
}

2022-03-07 07:53:11,204 INFO    MainThread:699817 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 15674
}

2022-03-07 07:53:11,306 INFO    MainThread:699817 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15674
  total_bytes: 15674
}

2022-03-07 07:53:11,408 INFO    MainThread:699817 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15674
  total_bytes: 15674
}

2022-03-07 07:53:11,510 INFO    MainThread:699817 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15674
  total_bytes: 15674
}

2022-03-07 07:53:11,613 INFO    MainThread:699817 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15674
  total_bytes: 15674
}

2022-03-07 07:53:11,715 INFO    MainThread:699817 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15674
  total_bytes: 15674
}

2022-03-07 07:53:12,114 INFO    MainThread:699817 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15674
  total_bytes: 15674
}

2022-03-07 07:53:13,778 INFO    MainThread:699817 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15674
  total_bytes: 15674
}
local_info {
}

2022-03-07 07:53:14,844 INFO    MainThread:699817 [wandb_run.py:_append_files():2180] logging synced files
