2022-02-28 15:41:24,451 INFO    MainThread:625255 [wandb_setup.py:_flush():71] setting env: {}
2022-02-28 15:41:24,451 INFO    MainThread:625255 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-28 15:41:24,451 INFO    MainThread:625255 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-28 15:41:24,451 INFO    MainThread:625255 [wandb_init.py:_log_setup():371] Logging user logs to /home/junshick/Workspace/pose_estimation/custom_pose/wandb/run-20220228_154124-4lih0ecj/logs/debug.log
2022-02-28 15:41:24,451 INFO    MainThread:625255 [wandb_init.py:_log_setup():372] Logging internal logs to /home/junshick/Workspace/pose_estimation/custom_pose/wandb/run-20220228_154124-4lih0ecj/logs/debug-internal.log
2022-02-28 15:41:24,452 INFO    MainThread:625255 [wandb_init.py:init():404] calling init triggers
2022-02-28 15:41:24,452 INFO    MainThread:625255 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2022-02-28 15:41:24,452 INFO    MainThread:625255 [wandb_init.py:init():460] starting backend
2022-02-28 15:41:24,452 INFO    MainThread:625255 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-28 15:41:24,459 INFO    MainThread:625255 [backend.py:ensure_launched():216] starting backend process...
2022-02-28 15:41:24,462 INFO    MainThread:625255 [backend.py:ensure_launched():222] started backend process with pid: 625264
2022-02-28 15:41:24,463 INFO    MainThread:625255 [wandb_init.py:init():469] backend started and connected
2022-02-28 15:41:24,464 INFO    MainThread:625255 [wandb_init.py:init():533] updated telemetry
2022-02-28 15:41:24,466 INFO    MainThread:625255 [wandb_init.py:init():563] communicating current version
2022-02-28 15:41:24,920 INFO    MainThread:625255 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.10 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-02-28 15:41:24,921 INFO    MainThread:625255 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-02-28 15:41:25,197 INFO    MainThread:625255 [wandb_init.py:init():606] starting run threads in backend
2022-02-28 15:41:27,777 INFO    MainThread:625255 [wandb_run.py:_console_start():1810] atexit reg
2022-02-28 15:41:27,778 INFO    MainThread:625255 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2022-02-28 15:41:27,778 INFO    MainThread:625255 [wandb_run.py:_redirect():1689] Redirecting console.
2022-02-28 15:41:27,779 INFO    MainThread:625255 [wandb_run.py:_redirect():1745] Redirects installed.
2022-02-28 15:41:27,779 INFO    MainThread:625255 [wandb_init.py:init():633] run started, returning control to user process
2022-02-28 15:41:41,721 INFO    MainThread:625255 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 255
2022-02-28 15:41:41,724 INFO    MainThread:625255 [wandb_run.py:_restore():1752] restore
2022-02-28 15:41:44,309 INFO    MainThread:625255 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 681
  total_bytes: 681
}

2022-02-28 15:41:44,605 INFO    MainThread:625255 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 681
  total_bytes: 681
}

2022-02-28 15:41:45,210 INFO    MainThread:625255 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 681
  total_bytes: 16626
}

2022-02-28 15:41:45,312 INFO    MainThread:625255 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 681
  total_bytes: 16626
}

2022-02-28 15:41:45,417 INFO    MainThread:625255 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 681
  total_bytes: 16626
}

2022-02-28 15:41:45,519 INFO    MainThread:625255 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 6596
  total_bytes: 16626
}

2022-02-28 15:41:45,621 INFO    MainThread:625255 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 16626
  total_bytes: 16626
}

2022-02-28 15:41:45,723 INFO    MainThread:625255 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 16626
  total_bytes: 16626
}

2022-02-28 15:41:45,826 INFO    MainThread:625255 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 16626
  total_bytes: 16626
}

2022-02-28 15:41:45,928 INFO    MainThread:625255 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 16626
  total_bytes: 16626
}

2022-02-28 15:41:46,031 INFO    MainThread:625255 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 16626
  total_bytes: 16626
}

2022-02-28 15:41:46,681 INFO    MainThread:625255 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 16626
  total_bytes: 16626
}

2022-02-28 15:41:47,234 INFO    MainThread:625255 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 16626
  total_bytes: 16626
}
local_info {
}

2022-02-28 15:41:48,300 INFO    MainThread:625255 [wandb_run.py:_append_history():2130] rendering history
2022-02-28 15:41:48,301 INFO    MainThread:625255 [wandb_run.py:_append_summary():2085] rendering summary
2022-02-28 15:41:48,301 INFO    MainThread:625255 [wandb_run.py:_append_files():2180] logging synced files
