2022-03-07 10:12:52,131 INFO    MainThread:702592 [wandb_setup.py:_flush():71] setting env: {}
2022-03-07 10:12:52,131 INFO    MainThread:702592 [wandb_setup.py:_flush():71] setting login settings: {}
2022-03-07 10:12:52,131 INFO    MainThread:702592 [wandb_setup.py:_flush():71] setting login settings: {}
2022-03-07 10:12:52,131 INFO    MainThread:702592 [wandb_init.py:_log_setup():371] Logging user logs to /home/junshick/Workspace/pose_estimation/custom_pose/wandb/run-20220307_101252-4xzxvi0s/logs/debug.log
2022-03-07 10:12:52,131 INFO    MainThread:702592 [wandb_init.py:_log_setup():372] Logging internal logs to /home/junshick/Workspace/pose_estimation/custom_pose/wandb/run-20220307_101252-4xzxvi0s/logs/debug-internal.log
2022-03-07 10:12:52,131 INFO    MainThread:702592 [wandb_init.py:init():404] calling init triggers
2022-03-07 10:12:52,131 INFO    MainThread:702592 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2022-03-07 10:12:52,131 INFO    MainThread:702592 [wandb_init.py:init():460] starting backend
2022-03-07 10:12:52,131 INFO    MainThread:702592 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-07 10:12:52,138 INFO    MainThread:702592 [backend.py:ensure_launched():216] starting backend process...
2022-03-07 10:12:52,142 INFO    MainThread:702592 [backend.py:ensure_launched():222] started backend process with pid: 702601
2022-03-07 10:12:52,142 INFO    MainThread:702592 [wandb_init.py:init():469] backend started and connected
2022-03-07 10:12:52,144 INFO    MainThread:702592 [wandb_init.py:init():533] updated telemetry
2022-03-07 10:12:52,156 INFO    MainThread:702592 [wandb_init.py:init():563] communicating current version
2022-03-07 10:12:52,606 INFO    MainThread:702592 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-03-07 10:12:52,606 INFO    MainThread:702592 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-03-07 10:12:52,885 INFO    MainThread:702592 [wandb_init.py:init():606] starting run threads in backend
2022-03-07 10:12:55,484 INFO    MainThread:702592 [wandb_run.py:_console_start():1810] atexit reg
2022-03-07 10:12:55,484 INFO    MainThread:702592 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2022-03-07 10:12:55,485 INFO    MainThread:702592 [wandb_run.py:_redirect():1689] Redirecting console.
2022-03-07 10:12:55,485 INFO    MainThread:702592 [wandb_run.py:_redirect():1745] Redirects installed.
2022-03-07 10:12:55,485 INFO    MainThread:702592 [wandb_init.py:init():633] run started, returning control to user process
2022-03-07 10:13:21,579 INFO    MainThread:702592 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 255
2022-03-07 10:13:21,579 INFO    MainThread:702592 [wandb_run.py:_restore():1752] restore
